version: 2.1

parameters:
    tests_to_run:
        type: string
        default: 'tests

          with new

          lines'

jobs:
    # Fetch the tests to run
    run_tests:
        working_directory: ~/transformers
        docker:
            - image: cimg/python:3.7.12
        steps:
            - checkout
            - attach_workspace:
                at: ~/transformers/test_preparation
            - run: |
                if [ ! -s test_preparation/test_list.txt ]; then
                    echo "No tests to run, exiting early!"
                else 
                    echo "Found tests!"
                    cat test_preparation/test_list.txt
                fi
            - run: echo << pipeline.parameters.tests_to_run >>

workflows:
    version: 2
    run_tests:
        jobs:
            - run_tests
    